AWSTemplateFormatVersion: '2010-09-09'
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'bookmark-s3'
      NotificationConfiguration:
        QueueConfigurations:
          - Event: 's3:ObjectCreated:*'
            Filter:
              S3Key:
                Rules:
                  - Name: 'prefix'
                    Value: 'csv/'
                  - Name: 'suffix'
                    Value: '.csv'
            Queue: !GetAtt SQSQueue.Arn

  SQSQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: 'bookmark-csv-sqs'

  SQSQueuePolicy:
    Type: 'AWS::SQS::QueuePolicy'
    Properties:
      Queues:
        - !Ref SQSQueue
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal: '*'
            Action: 'SQS:SendMessage'
            Resource: !GetAtt SQSQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Sub 'arn:aws:s3:::bookmark-s3'

  S3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 's3.amazonaws.com'
            Action: 'sqs:SendMessage'
            Resource: !GetAtt SQSQueue.Arn
            Condition:
              ArnLike:
                aws:SourceArn: !Sub 'arn:aws:s3:::bookmark-s3'

Outputs:
  S3BucketName:
    Description: 'The name of the S3 bucket'
    Value: !Ref S3Bucket

  SQSQueueName:
    Description: 'The name of the SQS queue'
    Value: !Ref SQSQueue

  SQSQueueArn:
    Description: 'The ARN of the SQS queue'
    Value: !GetAtt SQSQueue.Arn
